### ISSUE TITLE
match by value type

### ISSUE THREAD

**Issue by punund** [tckerr/walk#1]
I wonder if we can match nodes not only by keys belonging to classes, but also by value types, by runing a check similar to 
```js
   {}.toString.call(x).slice(8, -1)
```
to get a meaningful type (`Number`, `Date` etc.) and then call a corresponging callback.

**Comment by tckerr** [comment]
Thanks for opening an issue. 

I don't quite understand your example, but you can always provide custom filters by adding a precondition check in the callback itself. For example:

```javascript
{
   ...
   callback: (node) => {
      if(typeof node.val !== 'object') return
      // do processing here
    }
}
```
