### ISSUE TITLE
Depth-first walk, skip children

### ISSUE THREAD

**Issue by miquik** [tckerr/walk#14]
Hi,
Would it be possible to 'skip' visiting the children of a given node in depth-first mode?

**Comment by tckerr** [comment]
In the current version of the library, filters only apply to a node but it won't affect the processing of their children. I had never thought about this until you brought it up, and I could see an argument for not processing filtered nodes' children, although that would be a breaking change.

In the meantime, you can filter on the node's `ancestors` to achieve your goal. See below:


```typescript
const data = {
    basket: {
        fruit: {
            apple: 1,
            banana: 2
        }
    }
}
function shouldBeSkipped(node: WalkNode): boolean {
    // put your logic for identifying the node to skip here
    return node.ancestors.some(a => a.key === 'basket')
}
walk(data, {
    traversalMode: "depth",
    onVisit: [
        {
            filters: node => !shouldBeSkipped(node),
            callback: node => {
                // put your logic here
            }
        }
    ]
})
```
